name: Build IPA

on:
  push:
    branches: [ "main", "feature/cicd-flutter-gh-bb-azure" ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10

    env:
      IOS_INFO_PLIST: ExportOptions.plist
      BUNDLE_IDENTIFIER: com.appambit.testapp
      ARTIFACT_NAME: appambit-test-app-release-ipa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.4'

      - name: Install certificate and provisioning profile
        shell: bash
        env:
          IOS_BUILD_CERTIFICATE_BASE64: ${{ secrets.IOS_P12_CERTIFICATE_BASE64 }}
          IOS_BUILD_CERTIFICATE_PASSWORD: ${{ secrets.IOS_APPLE_P12_PASSWORD }}
          IOS_MOBILE_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
          IOS_GITHUB_KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          PP_PATH=$RUNNER_TEMP/temp.mobileprovision

          echo -n "$IOS_BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$IOS_MOBILE_PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          security create-keychain -p "$IOS_GITHUB_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$IOS_GITHUB_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          security import $CERTIFICATE_PATH -P "$IOS_BUILD_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security find-identity -v

          UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i $PP_PATH))

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
          echo "Provisioning profile UUID: $UUID"

      - name: Create ExportOptions.plist file
        working-directory: appambit_sdk_flutter/appambit_test_app/ios
        run: |
          cat > $IOS_INFO_PLIST <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>compileBitcode</key>
            <true/>
            <key>method</key>
            <string>ad-hoc</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${{ env.BUNDLE_IDENTIFIER }}</key>
              <string>${{ secrets.IOS_ADHOC_PROFILE }}</string>
            </dict>
            <key>signingCertificate</key>
            <string>iPhone Distribution</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>teamID</key>
            <string>${{ secrets.IOS_APPLE_TEAM_ID }}</string>
            <key>thinning</key>
            <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      - name: Get dependencies
        working-directory: appambit_sdk_flutter
        run: flutter pub get

      - name: Build release IPA
        working-directory: appambit_sdk_flutter/appambit_test_app
        run: flutter build ipa --release --export-options-plist ios/${{ env.IOS_INFO_PLIST }}

      - name: Upload release IPA
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: appambit_sdk_flutter/appambit_test_app/build/ios/ipa/