name: Build APK

on:
  push:
    branches: [ "main", "feature/cicd-flutter-gh-bb-azure" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      KEYSTORE_FILE_NAME: appambit.keystore
      ARTIFACT_NAME: app_appambit_testapp
      APK_PATH: appambit_sdk_flutter/appambit_test_app/build/app/outputs/flutter-apk/app-release.apk
      ROOT_DIR: appambit_sdk_flutter
      TYPE_RELEASE: alpha

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "18"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.4'

      - name: Get dependencies
        working-directory: ${{ env.ROOT_DIR }}
        run: flutter pub get

      - name: Create keystore and key.properties
        working-directory: ${{ env.ROOT_DIR }}/appambit_test_app/android
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > ${{ env.KEYSTORE_FILE_NAME }}

          cat <<EOF > key.properties
          keyAlias=${KEY_ALIAS}
          keyPassword=${KEY_PASSWORD}
          storeFile=../${{ env.KEYSTORE_FILE_NAME }}
          storePassword=${KEYSTORE_PASSWORD}
          EOF
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build release APK
        working-directory: ${{ env.ROOT_DIR }}/appambit_test_app
        run: flutter build apk --release

      - name: Rename APK output
        run: |
          ORIGINAL_APK=${{ env.APK_PATH }}
          DIR=$(dirname "$ORIGINAL_APK")
          NEW_NAME="${{ env.ARTIFACT_NAME }}_${{ env.TYPE_RELEASE }}.apk"
          echo "Renaming $ORIGINAL_APK â†’ $DIR/$NEW_NAME"
          mv "$ORIGINAL_APK" "$DIR/$NEW_NAME"
          
          echo "APK_PATH=$DIR/$NEW_NAME" >> $GITHUB_ENV

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}_${{ env.TYPE_RELEASE }}
          path: ${{ env.APK_PATH }}