name: Build IPA

on:
  push:
    branches: 'feature/*'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10

    env:
      IOS_INFO_PLIST: ExportOptions.plist
      BUNDLE_IDENTIFIER: com.AppAmbit.TestApp
      ARTIFACT_NAME: appambit-test-app-release-ipa
      IPA_NAME: app_appambit_testapp
      ROOT_DIR: appambit_sdk_flutter
      TEST_PROJECT_NAME: appambit_test_app
      FLUTTER_VERSION: '3.35.4'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Validate and extract release type from branch name
#        run: |
#          FULL_BRANCH="${GITHUB_REF#refs/heads/}"
#
#          if [[ "$FULL_BRANCH" == alpha/* || "$FULL_BRANCH" == beta/* || "$FULL_BRANCH" == production/* ]]; then
#            TYPE_RELEASE="${FULL_BRANCH%%/*}"
#            echo "TYPE_RELEASE=$TYPE_RELEASE" >> $GITHUB_ENV
#          else
#            echo "Branch '$FULL_BRANCH' does not start with alpha/, beta/ or production/. Exiting..."
#            exit 1
#          fi

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install certificate and provisioning profile
        shell: bash
        env:
          IOS_BUILD_CERTIFICATE_BASE64: ${{ secrets.IOS_P12_CERTIFICATE_BASE64 }}
          IOS_BUILD_CERTIFICATE_PASSWORD: ${{ secrets.IOS_APPLE_P12_PASSWORD }}
          IOS_MOBILE_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
          IOS_GITHUB_KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          PP_PATH=$RUNNER_TEMP/temp.mobileprovision

          echo -n "$IOS_BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$IOS_MOBILE_PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          security create-keychain -p "$IOS_GITHUB_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$IOS_GITHUB_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          security import $CERTIFICATE_PATH -P "$IOS_BUILD_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security find-identity -v

          UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i $PP_PATH))

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
          echo "Provisioning profile UUID: $UUID"

      - name: Create ExportOptions.plist file
        working-directory: ${{ env.ROOT_DIR }}/{{ env.TEST_PROJECT_NAME }}/ios
        run: |
          cat > $IOS_INFO_PLIST <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>compileBitcode</key>
            <true/>
            <key>method</key>
            <string>ad-hoc</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${{ env.BUNDLE_IDENTIFIER }}</key>
              <string>${{ secrets.IOS_ADHOC_PROFILE }}</string>
            </dict>
            <key>signingCertificate</key>
            <string>iPhone Distribution</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>teamID</key>
            <string>${{ secrets.IOS_APPLE_TEAM_ID }}</string>
            <key>thinning</key>
            <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      - name: Get dependencies
        working-directory: ${{ env.ROOT_DIR }}
        run: flutter pub get

      - name: Build release IPA
        working-directory: ${{ env.ROOT_DIR }}/{{ env.TEST_PROJECT_NAME }}
        run: flutter build ipa --release --export-options-plist ios/${{ env.IOS_INFO_PLIST }}

      - name: Rename IPA output
        run: |
          ORIGINAL_IPA=$(find ${{ env.ROOT_DIR }}/{{ env.TEST_PROJECT_NAME }}/build/ios/ipa -name "*.ipa" | head -n 1)
          echo "IPA founded: $ORIGINAL_IPA"
          DIR=$(dirname "$ORIGINAL_IPA")
          mkdir -p $RUNNER_TEMP/artifact
          NEW_IPA_NAME="${{ env.IPA_NAME }}_${{ env.TYPE_RELEASE }}.ipa"
          cp "$ORIGINAL_IPA" "$RUNNER_TEMP/artifact/$NEW_IPA_NAME"
          echo "IPA renamed: $NEW_IPA_NAME"
          echo "Final IPA path: $RUNNER_TEMP/artifact/$NEW_IPA_NAME"
          echo "NEW_IPA_PATH=$RUNNER_TEMP/artifact/$NEW_IPA_NAME" >> $GITHUB_ENV

      - name: Upload renamed IPA
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IPA_NAME }}_${{ env.TYPE_RELEASE }}
          path: ${{ env.NEW_IPA_PATH }}