name: Build IPA

on:
  push:
    branches: [ "main", "feature/cicd-flutter-gh-bb-azure" ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10

    env:
      IOS_INFO_PLIST: ExportOptions.plist
      BUNDLE_IDENTIFIER: com.appambit.testapp
      ARTIFACT_NAME: appambit-test-app-release-ipa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.4'

      - name: Reset Keychain Environment
        run: |
          security delete-keychain build.keychain || true
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -l build.keychain
      
      - name: Decode and install P12 certificate
        env:
          P12_CERTIFICATE_BASE64: ${{ secrets.IOS_P12_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.IOS_APPLE_P12_PASSWORD }}
        run: |
          echo "$P12_CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Decode and install Provisioning Profile
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
        run: |
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          UUID=$(security cms -D -i profile.mobileprovision | plutil -extract UUID xml1 -o - - | xmllint --xpath "string(//string)" -)
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
          echo "UUID=$UUID" >> $GITHUB_ENV
      
      - name: Create ExportOptions.plist file
        working-directory: appambit_sdk_flutter/appambit_test_app/ios
        run: |
          cat > $IOS_INFO_PLIST <<EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>compileBitcode</key>
              <true/>
              <key>method</key>
              <string>release-testing</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>{{ env.BUNDLE_IDENTIFIER }}</key>
                <string>${{ secrets.IOS_ADHOC_PROFILE}}</string>
              </dict>
              <key>signingCertificate</key>
              <string>iPhone Distribution</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>teamID</key>
              <string>${{ secrets.IOS_APPLE_TEAM_ID }}</string>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
            </dict>
            </plist>
            EOF

      - name: Verify ExportOptions.plist
        working-directory: appambit_sdk_flutter/appambit_test_app/ios
        run: |
          ls -l

      - name: Get dependencies
        working-directory: appambit_sdk_flutter
        run: flutter pub get

      - name: Build release IPA
        working-directory: appambit_sdk_flutter/appambit_test_app
        run: flutter build ipa --release --export-options-plist ios/${{ env.IOS_INFO_PLIST }}

      - name: Upload release IPA
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: appambit_sdk_flutter/appambit_test_app/build/ios/ipa/${{ env.IOS_APP_NAME }}